Work around OpenSSL issue with AWS CLI v2
When running the AWS CLI v2 it fails with what appears to be an OpenSSL
version/compatibility issue. To work around this update to a more
current version of OpenSSL

Issue:
```
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```